version: '3'
services:
  ches-dashboard:
    depends_on:
      - ches-db
    container_name: ches-dashboard
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    networks:
      - ches_network
    volumes:
      - "./volumes/web/settings.py:/root/core/settings.py"
  ches-db:
    image: postgres:latest
    container_name: ches-db
    restart: always
    volumes:
      - "./volumes/pg-init-scripts:/docker-entrypoint-initdb.d"
      - "./volumes/db/data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime"
    environment:
      POSTGRES_USER: chesadmin
      POSTGRES_PASSWORD: spacedebris
      POSTGRES_MULTIPLE_DATABASES: ches,chessite,chesweb
    ports:
      - "5432:5432"
    networks:
      - ches_network
networks:
  ches_network:
    driver: bridge
 
