# Generated by Django 3.2.5 on 2021-08-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('coord', models.JSONField(blank=True, null=True)),
                ('last_obstime', models.DateTimeField(blank=True, null=True)),
                ('last_obstel', models.IntegerField(blank=True, null=True)),
                ('total_times', models.IntegerField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('filepath', models.CharField(blank=True, max_length=200, null=True)),
                ('telid', models.IntegerField(blank=True, null=True)),
                ('plan', models.CharField(blank=True, max_length=30, null=True)),
                ('usrid', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=8, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('mag_limit', models.FloatField(blank=True, null=True)),
                ('astrometry', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('tel_id', models.CharField(blank=True, max_length=10, null=True)),
                ('usr_id', models.IntegerField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('request_fields', models.JSONField(blank=True, null=True)),
                ('guide_data', models.JSONField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('datapath', models.CharField(blank=True, max_length=200, null=True)),
                ('proposal', models.IntegerField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mount_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('target_ra', models.FloatField(blank=True, null=True)),
                ('target_dec', models.FloatField(blank=True, null=True)),
                ('mount_info', models.JSONField(blank=True, null=True)),
                ('cam_status', models.CharField(blank=True, max_length=20, null=True)),
                ('filter', models.CharField(blank=True, max_length=5, null=True)),
                ('ccd_temp', models.IntegerField(blank=True, null=True)),
                ('cooling_power', models.IntegerField(blank=True, null=True)),
                ('cam_info', models.JSONField(blank=True, null=True)),
                ('free_space', models.FloatField(blank=True, null=True)),
                ('run_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
    ]
