# Generated by Django 3.2.6 on 2021-08-06 16:51

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='run_level',
        ),
        migrations.AlterField(
            model_name='status',
            name='cam_info',
            field=app.models.JSONFieldJSONType(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='mount_info',
            field=app.models.JSONFieldJSONType(blank=True, null=True),
        ),
    ]
