# Generated by Django 3.2.6 on 2021-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210807_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='run_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
